from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Packet:
    """
    Represents one packet generated by a sensor node.
    """

    packet_id: int
    source_id: int
    destination_id: int
    payload: str

    current_node_id: int
    route: list[int] = field(default_factory=list)

    delivered: bool = False
    dropped: bool = False
    drop_reason: str | None = None

    hop_count: int = 0

    def add_hop(self, node_id: int) -> None:
        """
        Add a node to the packet's travelled route.
        """

        self.route.append(node_id)
        self.current_node_id = node_id
        self.hop_count = max(0, len(self.route) - 1)